part of '../main.dart';

Widget _buildLifeHomeModulePage({
  required LifeModule module,
  required ValueChanged<LifeModule> onSwitchModule,
  required VoidCallback onOpenModules,
  required VoidCallback onOpenQuickRecord,
  required int foodCalories,
  required int workoutGroups,
  required Map<String, int> workoutGroupsByAction,
  required List<WorkoutPlan> workoutPlans,
  required ActiveWorkoutSession? activeWorkoutSession,
  required List<WorkoutHistoryEntry> workoutHistory,
  required List<TodoItem> todos,
  required List<LifeEvent> events,
  required List<FinanceRecord> financeRecords,
  required double todayExpense,
  required String aiFinanceEndpoint,
  required String aiFinanceModel,
  required String aiFinanceApiKey,
  required ValueChanged<FinanceRecord> onAddFinanceRecord,
  required void Function(FinanceRecord oldRecord, FinanceRecord newRecord)
      onEditFinanceRecord,
  required void Function({
    required String endpoint,
    required String model,
    required String apiKey,
  }) onUpdateAiFinanceConfig,
  required ValueChanged<int> onRecordFoodCalories,
  required void Function(String actionName, int finishedGroups)
      onUpdateWorkoutGroups,
  required ValueChanged<ActiveWorkoutSession> onStartWorkoutSession,
  required ValueChanged<ActiveWorkoutSession> onUpdateWorkoutSession,
  required ValueChanged<WorkoutHistoryEntry> onFinishWorkoutSession,
  required ValueChanged<TodoItem> onToggleTodo,
  required ValueChanged<TodoItem> onUpdateTodo,
  required ValueChanged<TodoItem> onPostponeTodo,
  required ValueChanged<TodoItem> onArchiveTodo,
  required ValueChanged<TodoItem> onDeleteTodo,
  required ValueChanged<TodoItem> onAddTodo,
  required VoidCallback onClearCompletedTodos,
  required WidgetQuickAction? quickAction,
  required int quickActionToken,
  required VoidCallback onQuickActionHandled,
}) {
  final moduleNav = _ModuleLinkStrip(
    selected: module,
    onSwitchModule: onSwitchModule,
  );
  return switch (module) {
    LifeModule.finance => FinanceModulePage(
        moduleNav: moduleNav,
        onOpenModules: onOpenModules,
        onSwitchModule: onSwitchModule,
        foodCalories: foodCalories,
        workoutGroups: workoutGroups,
        records: financeRecords,
        onAddRecord: onAddFinanceRecord,
        onEditRecord: onEditFinanceRecord,
        aiEndpoint: aiFinanceEndpoint,
        aiModel: aiFinanceModel,
        aiApiKey: aiFinanceApiKey,
        onAiConfigChanged: onUpdateAiFinanceConfig,
        quickAction: quickAction,
        quickActionToken: quickActionToken,
        onQuickActionHandled: onQuickActionHandled,
      ),
    LifeModule.plan => PlanModulePage(
        moduleNav: moduleNav,
        onOpenModules: onOpenModules,
        onSwitchModule: onSwitchModule,
        onOpenQuickRecord: onOpenQuickRecord,
        foodCalories: foodCalories,
        workoutGroups: workoutGroups,
        todayExpense: todayExpense,
        healthStatusText: '正常',
        todos: todos,
        events: events,
        onToggleTodo: onToggleTodo,
        onUpdateTodo: onUpdateTodo,
        onPostponeTodo: onPostponeTodo,
        onArchiveTodo: onArchiveTodo,
        onDeleteTodo: onDeleteTodo,
        onAddTodo: onAddTodo,
        onClearCompletedTodos: onClearCompletedTodos,
        quickAction: quickAction,
        quickActionToken: quickActionToken,
        onQuickActionHandled: onQuickActionHandled,
      ),
    LifeModule.food => FoodModulePage(
        moduleNav: moduleNav,
        onOpenModules: onOpenModules,
        onSwitchModule: onSwitchModule,
        onRecordCalories: onRecordFoodCalories,
        foodCalories: foodCalories,
        workoutGroups: workoutGroups,
        quickAction: quickAction,
        quickActionToken: quickActionToken,
        onQuickActionHandled: onQuickActionHandled,
      ),
    LifeModule.workout => WorkoutModulePage(
        moduleNav: moduleNav,
        onOpenModules: onOpenModules,
        onSwitchModule: onSwitchModule,
        finishedGroupsByAction: workoutGroupsByAction,
        onUpdateActionGroups: onUpdateWorkoutGroups,
        workoutPlans: workoutPlans,
        activeWorkoutSession: activeWorkoutSession,
        workoutHistory: workoutHistory,
        onStartWorkoutSession: onStartWorkoutSession,
        onUpdateWorkoutSession: onUpdateWorkoutSession,
        onFinishWorkoutSession: onFinishWorkoutSession,
        foodCalories: foodCalories,
        quickAction: quickAction,
        quickActionToken: quickActionToken,
        onQuickActionHandled: onQuickActionHandled,
      ),
    LifeModule.health => HealthModulePage(
        moduleNav: moduleNav,
        onOpenModules: onOpenModules,
        onSwitchModule: onSwitchModule,
        foodCalories: foodCalories,
        workoutGroups: workoutGroups,
        quickAction: quickAction,
        quickActionToken: quickActionToken,
        onQuickActionHandled: onQuickActionHandled,
      ),
  };
}
